### ISSUE TITLE
Use `useDeviceContext` from twrnc to get dark, light, and {spacing}-screen classes

### ISSUE THREAD

**Issue by ztcollazo** [finkef/react-native-tailwind.macro#12]
I've been trying to use the `w-screen` class, but I keep getting a twrnc warning that says to use `useDeviceContext` so that it can calculate the `vw` and `vh` values. I looked through the source code, and it doesn't look like this project it using it. What I would recommend is exporting the `tw` variable, importing it into the context file, and using the hook on it so that we can use these classes. This would be extremely helpful. Thanks! Love this project!

(P.S. If you want me to open a PR, I can do that also.)

**Comment by ztcollazo** [comment]
@finkef Actually I've looked at the `twrnc` source code, and it looks like much of the code that you use to get information such as screen width and such could be done inside of `twrnc`. After looking at the source code again, I realized that you may not be able to use the hook, but you could still use `Dimensions.get` with `Dimensions.addEventListener` to update the `tw` variable's prefixes; see [tailwind-react-native-classnames/hooks.ts](https://github.com/jaredh159/tailwind-react-native-classnames/blob/65bdb50365a2b1a8a65063747dcad727373e3dfa/src/hooks.ts#L13-L20) and [react-native/useWindowDimensions.js](https://github.com/facebook/react-native/blob/8bd3edec88148d0ab1f225d2119435681fbbba33/Libraries/Utilities/useWindowDimensions.js#L21-L46). It shouldn't be that hard and could replace a good bit of platform-specific code. Again, if you so desire, I can submit a PR given some time.

**Comment by finkef** [comment]
The problem is that all styles are calculated by the macro during compilation, meaning that changes to `Dimensions` wouldn't ever be shown. Hadn't encountered that use case yet in any of my projects using the macro, but this might be one of the caveats.

Depending on the specific case, I think you can work around this issue by having `flex` manage width and heights. Alternatively, you can always fallback to `style={{ width: Dimensions.get("window").width }}`.

**Comment by ztcollazo** [comment]
Thanks! That problem makes sense. I'll use your other recommended methods.
